spring:
  application:
    name: trading-agent

  # MySQL Database Configuration (Production)
  datasource:
    url: ${DB_URL:jdbc:mysql://database-1-instance-1.cjrl4eygvoqi.us-east-1.rds.amazonaws.com:3306/tradingagent?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:QuantumHusky2025}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none  # Disable auto DDL in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: tradingagent

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-production-secret-key-must-be-at-least-256-bits-long-change-this}
  expiration: 86400000  # 24 hours in milliseconds

# Python Service Configuration
python:
  service:
    url: ${PYTHON_SERVICE_URL:http://52.201.180.132:8000}

# Stripe Configuration
stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_51SKMM2J3N6QMImyOls9TqpQTphljl0tFRAPydQbwo8VF52exksrE08DyXtWq9XVHqTyY1SiOnfYtwCWPehgTSIDx006X7C2tH2}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_51SKMM2J3N6QMImyOoRKmtnccq1tPRc8eEfs5aIxpTLAvPp6TtWfbVgMDPqaRLArZnrrPp84dEHePVApsaIov9U4D00s8c2xyXH}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_cfb971496aee47e924ed33d262f1ab777beadb7c24fadbcc7ec80eb7111cd378}
  currency: ${STRIPE_CURRENCY:usd}

# Billing Configuration
billing:
  free-task-limit: ${FREE_TASK_LIMIT:5}
  default-pricing-strategy: ${PRICING_STRATEGY_CODE:DEFAULT_2024}
  price-cache-ttl-seconds: ${PRICING_CACHE_TTL_SECONDS:300}

# Server Configuration
server:
  port: ${SERVER_PORT:8080}

# CORS Configuration
cors:
  allowedOrigins:
    - "https://sandbox.quantumhusky.ai"
    - "http://sandbox.quantumhusky.ai"
    - "http://localhost:3000"
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowedHeaders:
    - "*"
  allowCredentials: true

# Logging Configuration
# Detailed logging configuration is in logback-spring.xml
logging:
  config: classpath:logback-spring.xml
